[build]
  publish = "Codigo"
  command = "npm run build"

[[headers]]
  for = "/*"
    [headers.values]
      Access-Control-Allow-Origin = "*"

[[redirects]]
  from = "/*"
  to = "/main.html"
  status = 200

[[redirects]]
  from = "/"
  to = "/main.html"
  status = 200

[[redirects]]
  from = "/home"
  to = "/main.html"
  status = 200
